#!/bin/bash
## Use current working directory (change working directory)
##Error file
#$ -e /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SAPA93/admixture/ADMIXTURE_SAPA93_iterate.err
## Out file
#$ -o /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SAPA93/admixture/ADMIXTURE_SAPA93_iterate.out
#$ -S /bin/bash
## Job's name
#$ -N ADMIXTURE_Mezcal
#$ -l vf=8G
#$ -pe openmp 4
#$ -m e
## notification
#$ -M jabrahamavelar@gmail.com

## Modules
module load vcftools/0.1.14 admixture/1.3.0 plink

## Remove prefix form chromosome numbers at chromosome names
cp originalMatrix.vcf Matrix.vcf # copy the vcf before changing chromosome names
sed -i 's/SAPA_YPS138_v1_chr_0//g' Matrix.vcf
sed -i 's/SAPA_YPS138_v1_chr_//g' Matrix.vcf

#Cómo guardar las salidas en pantalla en el SGE/st/*.out
#Ponerle Sufijo de la SampleSheet a los archivos
module load vcftools/0.1.14  
vcftools --vcf Matrix.vcf --plink --out Matrix  #  generate .ped .map and .log. 
module load plink                       # PLINK v1.90b6.26 64-bit (2 Apr 2022) (que carga si no le dices cuál) sí funciona. con el 1.07 no te hace el .fam con estas instrucciones
plink --file Matrix --out Matrix        # .log .bed .bim .fam
plink --bfile Matrix --indep-pairwise 500 10 .3  --out Matrix # SNP_window500 advancing_10SNPs_each_Time   r2_greater_than.3    # Outputs: .nosex .log .prune.out .prune.in
plink --bfile Matrix --extract Matrix.prune.in --make-bed --out Matrix_LDPrune # Matrix_LDPrune.log .bim .fam .bed .nosex
