#!/bin/bash
## Use current working directory (change working directory)
##Error file
#$ -e /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/admixture/ADMIXTURE_SACE304_iterate.err
## Out file
#$ -o /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/admixture/ADMIXTURE_SACE304_iterate.out
#$ -S /bin/bash
## Job's name
#$ -N ADMIXTURE_Mezcal
#$ -l vf=8G
#$ -pe openmp 4
#$ -m e
## notification
#$ -M jabrahamavelar@gmail.com

## Modules
module load admixture/1.3.0

for rseed in {1..10}
  do
  for K in {1..10}
  do
    admixture -s ${RANDOM} -B --cv /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/Matrix_LDPrune.bed $K -j4 |tee /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/logfiles/log_SACE304_${rseed}_${K}_LDprune.out
    mv /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/Matrix_LDPrune.{K}.Q /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/out/Matrix_LDPrune.K${K}.r${rseed}.Q
    mv /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/Matrix_LDPrune.{K}.P /mnt/Timina/lmorales/Public/ymez/tmp/06_genotyping/trees/SACE304/out/Matrix_LDPrune.K${K}.r${rseed}.P
  done
done
